apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: messaging-app
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "messanger"
  DB_USER: "guest"
  DB_PASSWORD: "guest"
  KAFKA_BROKERS: "kafka:9092"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production" 