apiVersion: v1
kind: Service
metadata:
  name: ws-service
  namespace: messaging-app
spec:
  selector:
    app: ws-service
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer 